version: "3"
services:
  grpc-server:
    container_name: grpc-server
    build:
      context: ./server
      dockerfile: Dockerfile
      
  grpc-client:
    container_name: grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SERVER_ADDRESS=grpc-server:50051
    #depend_on:
    #  - grpc-server